name: FIX LIBVVDEC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Git clone for vvdec and lehmann-c/FFmpeg
      run: git clone https://github.com/fraunhoferhhi/vvdec.git
    - name: Build and Install libvvdec
      run: cd vvdec && emcmake cmake -B build/wasm && cmake --build build/wasm && cd build/wasm
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
    # Filename for archive
        filename: vvdecjson
        path: ./*
        directory: ./*
        type: 7z
