name: Build vvc arm64 [IOS]
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Git clone vvdec
      run: git clone --depth=1 https://github.com/fraunhoferhhi/vvenc && git clone --depth=1 https://github.com/fraunhoferhhi/vvdec
    - name: Build vvenc
      run: cd vvenc && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. -G "Xcode" && cmake --build . --config Release --target install && cd ../../
    - name: Build vvdec
      run: cd vvdec && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. -G "Xcode" && cmake --build . --config Release --target install && cd ../../
    - name: Download dependicies for Brew
      uses: ConorMacBride/install-package@v1.0.0
      with:
        brew: ffmpeg libvmaf opus libopusenc sdl2 fdk-aac libxml2
    - name: Run and build FFmpeg
      run: git clone --depth=1 https://github.com/MartinEesmaa/FFmpeg && cd FFmpeg && chmod +x ./configure && ./configure --enable-libfdk-aac --enable-static --enable-libvvenc --enable-libvvdec --enable-pic --enable-zlib --enable-libxml2 --enable-libdav1d --enable-libopus --enable-libvmaf --extra-ldexeflags=-static --pkg-config-flags=-static --enable-sdl2 --extra-version=VVCEasy && make -j
    - name: Zip Release of vvdec
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: vvdec.zip
        path: ffmpeg ffplay ffprobe
    - name: Upload a Build Artifact of vvenc
      uses: actions/upload-artifact@v3.0.0
      with:
        name: vvdec
        path: ./vvdec.zip