name: Build a new Versatile Video Codec x86_64 / amd64 Intel CPU Progress Process Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Git clone vvdec
      run: git clone https://github.com/fraunhoferhhi/vvenc && git clone https://github.com/fraunhoferhhi/vvdec
    - name: Build vvenc
      run: cd vvenc && git checkout 8594a0f64a8c552fb640a2b33da7e592641f7c1e && mkdir build && cd build && cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 .. -G "Xcode" && cmake --build . --config Release && cd ../../
    - name: Build vvdec
      run: cd vvdec && git checkout b4b8b40b1f0323673d9efb0844e47b53576af15f && mkdir build && cd build && cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 .. -G "Xcode" && cmake --build . --config Release && cd ../../
    - name: Zip Release of vvenc
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: vvenc.zip
        path: ./vvenc/bin/release-static
    - name: Zip Release of vvdec
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: vvdec.zip
        path: ./vvdec/bin/release-static
    - name: Upload a Build Artifact of vvenc
      uses: actions/upload-artifact@v3.0.0
      with:
        name: vvenc
        path: ./vvenc.zip
    - name: Upload a Build Artifact of vvdec
      uses: actions/upload-artifact@v3.0.0
      with:
        name: vvdec
        path: ./vvdec.zip
